### ISSUE TITLE
Conduct a visual audit of materials

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1520]
### Task
**Review the existing Federalist artifacts and identify some opportunities to improve brand consistency and overall visual style (plus any ux concerns that surface in the process).**

### Definition of done
A starter set of suggested improvements have been documented as issues for the following:
- [x] [Marketing landing](https://federalist.fr.cloud.gov/) page
- [x] [Example sites](https://federalist.fr.cloud.gov/content/examples/) page
- [x] Google "Federalist interest" [signup form](https://docs.google.com/forms/d/e/1FAIpQLSesNI1qlov7Ec_1u2FralYWg9hV4WsB-3FyAHPXc1pRT6In7w/viewform)
- [x] [Documentation site](https://federalist-docs.18f.gov/)
- [ ] ~First-time login process~ Address later, if user issues arise
- [x] PDFs such as the [compliance memo](https://federalist-docs.18f.gov/assets/documents/Federalist-Compliance-Memo.pdf) and marketing [one-pager](https://federalist-docs.18f.gov/assets/documents/Federalist-One-Pager.pdf)
- [ ] ~The Federalist dashboard app itself,~ (Later) and

- [x] A summary of general recommendations has been drafted

@wslack pls feel free to comment, add anything i'm missing, and/or ~cross out~ any items you feel we don't need to bother with atm, thx.

**Comment by wslack** [comment]
👍  to prioritize (as discussed, just noting in writing)

and that list looks right, though we might move away from the interest signup form

**Comment by ericronne** [comment]
I've temporarily marked this as blocked because i want to glean insights on the overall branding direction from folks such as @OpenGlobe (spoke to already), @tram (tomorrow), and Phoebe Espiritu (also tomorrow). I'm especially curious to get their views on how the federalist and cloud.gov brands should overlap, and then to chat a bit with you on the topic, @wslack.

**Comment by wslack** [comment]
Ah interesting. There's a lot in that topic and I'm happy to talk mroe about it; just grab some time! (short answer is that there's flexibility IMO)

**Comment by ericronne** [comment]
Here's a doc with [some top-line thoughts](https://docs.google.com/document/d/1nG_hF4hpZC7flBCBaSBu9PXa0VZe6M8tkp9OP1Gu6bU/edit?usp=sharing) (and questions!).

@wslack let's discuss, then i can whip up some issues. Thx......

**Comment by wslack** [comment]
reassigning to @leahbannon per today

**Comment by ericronne** [comment]
issues have been issued.
closing book on this sucker.

_onward to execution!_

**Comment by wslack** [comment]
@ericronne remember to leave this in "Done?"
