### ISSUE TITLE
Evaluate Jekyll template strategy with USWDS

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1747]
#### Description of feature or bug

Review [uswds-jekyll](https://github.com/18F/uswds-jekyll) and how it is used by customers as well as our [Federalist templates](https://github.com/search?utf8=%E2%9C%93&q=federalist+template+org%3A18F&type=). Recommend any changes or document best practices to follow so it's clear to customers which template to use and how to keep up-to-date with the latest USWDS.

#### Definition of done

- [ ] Write up recommendations and mini-roadmap of how to approach the recommendations
- [ ] Documentation or recommendations on the relationship with USWDS team, including any workflows, support, and identifying ownership of processes or repositories
- [ ] Review the recommendations @wslack and Federalist team

_After evaluating, edit this part:_

#### Tasks

- [x] Technical review of the repos `uswds-jekyll` and `federalist-uswds-templates`
- [x] Chat with maintainers/contributors from `uswds-jekyll` and `federalist-uswds-templates` to understand goals and problem space
- [x] Review customer research from fall 2017 to incorporate user needs and pain points
- [x] Review current customer research to incorporate user needs and pain points
- [x] Chat with users of `uswds-jekyll` and `federalist-uswds-jekyll`
- [x] Chat with USWDS folks about their roadmap and support for these kinds of USWDS implementation projects.
- [x] Draft of recommendations for the team
- [x] Prototype any examples to help illustrate some of the recommendations as needed
- [x] Final "report" of recommendations

**Comment by wslack** [comment]
Also the relationship with the USWDS team maybe?

**Comment by adborden** [comment]
Good idea, added.

**Comment by adborden** [comment]
I'm going to call this a medium based on the scope.

**Comment by wslack** [comment]
agreed

**Comment by wslack** [comment]
Draft for review: https://docs.google.com/document/d/1WSwpiw44DAfHOSh3uyQlY8VybaN4shUYYAW6NLpLnl4/edit?usp=sharing
