### ISSUE TITLE
Create contact page for federalist.18f.gov (dev)

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1761]
#### User Story

As a Federalist user or potential user, I need a way to know how to contact the Federalist team and expect that be easily found.

#### Acceptance Criteria

- [ ] Page exists at `/contact`
- [ ] Page is linked from homepage

#### Implementation steps

- [x] Create a page framework for this content 
- [x] Page is populated with the content from #1795 
- [ ] Page is pushed to and displaying on staging.

#### Level of effort - low

**Comment by wslack** [comment]
Posted question about compliance here: https://gsa-tts.slack.com/archives/C039MHHF8/p1523472384000284

**Comment by ShannonBad** [comment]
Related content ideas for "contact us" on #1623

**Comment by annahsebok** [comment]
FYI: I've created #1795 to cover content needs for the contact page.

**Comment by wslack** [comment]
Converted to issue and marked other issues here with "Sales" label.

**Comment by line47** [comment]
👋 Howdy folks, I have some bandwidth this week and could get a contact page up 👍 
CC @wslack

**Comment by wslack** [comment]
THANK YOU @line47!

**Comment by annahsebok** [comment]
I moved a few pieces of the acceptance criteria from #1795 over to this issue (the ones that are relevant to front end work and not the content work). 🎉

**Comment by line47** [comment]
I wasn't sure on the layout/design of the page.
Here is a screenshot of what I have (took content from the Google doc referenced in https://github.com/18F/federalist/issues/1795

![contact](https://user-images.githubusercontent.com/1449852/41004527-31ee9104-68e8-11e8-8855-2f9ac1775d41.png)

**Comment by annahsebok** [comment]
This looks beautiful! Today got away from me but I may have some content updates in the AM. Will ping! Thanks for your patience. :)

**Comment by line47** [comment]
That sounds great, thanks!

**Comment by annahsebok** [comment]
@line47 I've made a few content updates [in our contact content](https://docs.google.com/document/d/1PYVw2IgRCuatdtpn1_0nKBL8JBV4i5VbyARnFJuzk3o/edit#heading=h.dw3s8g4gl893). If you can make those changes to the page you've created, that would be great! 

I also want to specifically call out (because I'm not seeing it in the design above) that it would be helpful for us to add the spacing between the paragraphs under **For existing Federalist users**. Otherwise it's a wall of text and that's no fun to look at. 😄 

Also, I'm not sure if this is a task for you or for somebody else, but I noticed that @wslack dropped a comment in the other issue about making a link like [this one](mailto:cloud-gov-inquiries@gsa.gov?body=What%27s%20your%20name%3F%0A%0AWhat%20agency%20or%20office%20do%20you%20work%20for%3F%0A%0AWhat%27s%20your%20job%20title%20or%20role%3F%0A%0ATell%20us%20a%20little%20about%20your%20project%20or%20your%20questions%20about%20cloud.gov:%0A%0AIf%20you%27d%20like%20us%20to%20call%20you%2C%20what%27s%20your%20phone%20number%20and%20when%20might%20be%20a%20good%20time%3F%0A) for _email the Federalist team_ and _submit a support ticket_ so that the requests are pre-populated with helpful contextual questions. Are you able to help with that or should we ping somebody else to scrub in?

**Comment by line47** [comment]
@annahsebok I can certainly help with that, I should be able to make some updates later today or tomorrow morning.

**Comment by annahsebok** [comment]
Huzzah! Thanks @line47!

**Comment by line47** [comment]
Just updated the content and the mailto link mentioned above! 
CC @annahsebok @wslack 
![screen shot 2018-06-08 at 2 00 20 pm](https://user-images.githubusercontent.com/1449852/41173232-1d2a4e14-6b24-11e8-9e20-4e8a90f0d389.png)
