### ISSUE TITLE
Upgrade Node before Node 6 is deprecated in April 2019 [start in October]

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#1967]
### User Story

As a Federalist developer and user, I want Federalist to use a current version of Node so that the app functions.

## #Background

The current release and support schedule for Node version is as follow.

<img src="https://github.com/nodejs/Release/raw/master/schedule.png">

Node 6 will not be supported after April 2019, we can move to Node 8, but that will EOL at the end December 2019. We should develop plan for supporting Node 10, which EOL April 2021.

More information can be found here: https://github.com/nodejs/Release

### Acceptance Criteria

- [x] Federalist runs using Node 10.
- [x] Federalist-builder runs using Node 10.
- [x] Federalist-garden-build container runtime runs using Node 10. (Node is available, even though code is in Python).
- [x] pages-redirects runs using Node 10.
- [x] Federalist-proxy runs using Node 10.
### Implementation Plan

_Should start in October after Node 10 Release (LTS) is out_

Level of effort - medium?

- [x] Update
- [x] Run Tests
- [x] Deploy to staging
- [x] See what happens!
- [x] Rinse and repeat for the other apps
