### ISSUE TITLE
Staffing Request

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2098]
**Designer or Front-End Engineer**

- [ ] Design a Federalist-wide 404/error page. [Current look](https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/ERROR)
- [ ]  Recommend/change [cartoony](https://federalist.18f.gov) graphics on Federalist website.

**Content**
- [ ] The [documentation for Federalist](https://federalist.18f.gov/pages/using-federalist/) jumps from topic to topic. We need a content person to update our language, labels, menus and headings to be more consistent. Here's the issue https://github.com/18F/uswds-jekyll/issues/153
- [ ] The [case studies](https://federalist.18f.gov/case-studies/) on the Federalist website needs to have a consistent tone.

**Engineer**
- [ ]  Implement a Federalist-wide 404/error page - *@alexsoble working on these*
- [ ] Close issues outlined on new USWDS 2.0 Federalist theme: 18F/federalist-uswds-jekyll/issues/14 to get it ready for 1.0.  **@adborden working on some of these**
- [ ] React/Gatsby engineer to help David Corwin create a new standard USWDS/React theme for Federalist. More information the issues can be found on the [repository](https://github.com/18F/federalist-uswds-gatsby)
- [ ] Investigate streaming [build logs](https://federalistapp.18f.gov/sites/3/builds/63831/logs) on Federalist app (would require knowledge of web sockets)
- [ ] We use a single docker image for all the types of builds, but we can optimize the build process by splitting them into smaller build images. https://github.com/18F/federalist-garden-build/issues/148
- @davemcorwin is working on Federalist issues

**Comment by annahsgraves** [comment]
@eddietejeda hello! have you seen the content strategy I created for the Federalist docs site to help with the content part of this? It's living in a mural somewhere, likely linked in one of my old content tickets from my work on Federalist. Cordelia and I put lots of legwork into that so could be useful as a starting point.

**Comment by eddietejeda** [comment]
Yes! Thanks.
