### ISSUE TITLE
Release plan for Federalist dedicated buckets

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#2236]
#### User Story

To support users being able to deploy sites to ~private~ **_dedicated_** buckets in production, a few steps will need to be completed and verified by a Federalist team member with access to the Federalist's cloud.gov production space.

##### Create User Provided Services

- [x] Create `federalist-production-space` user-provided service with the space's GUID
  - Run command:
  - ```cf cups federalist-production-space -p "{\"guid\": \"`cf space production --guid`\"}"```
- [x] Create `federalist-production-domain` user-provided service with the app.cloud.gov GUID
  - Run command:
  - ```cf cups federalist-production-space -p "{\"guid\": \"<APP.CLOUD.GOV DOMAIN GUID>\"}"```
- [x] Create `federalist-production-proxy` user-provided service with the federalist-proxy app GUID
  - Run command:
  - ```cf cups federalist-production-space -p "{\"guid\": \"`cf app federalist-proxy --guid`\"}"```
- [x] Verify `federalist-deploy-user` user-provided service is created and available in production
  - See [`federalist-builder`](https://github.com/18F/federalist-builder/blob/staging/manifest.yml#L11)
- [x] Map route to `federalist-proxy` based on the production, shared bucket name
  - Run command:
  - ```cf map-route federalist-proxy app.cloud.gov --hostname <PRODUCTION_S3_BUCKET_NAME>```
- [x] Update the "callback url" specified in the production Federalist OAuth application in Github to only be the federalist domain, ie (`https://federalistapp.18f.gov/`). (See #2230)
- [x] Add configuration for the Github external authentication callback url to `federalist-production-env` user-provided service: (See #2230)
  ```
  {
    "GITHUB_CLIENT_EXTERNAL_CALLBACK_URL": "https://federalistapp.18f.gov/external/auth/github/callback"`
  }
  ```
- [x] Create S3 service key
  `cf csk federalist-production-s3 federalist-production-s3-key`

##### Implementation Steps

- [x] **1st:** Create User Provided Services described above ☝️ in production environment.
- [x] **2nd:** Successfully merge and deploy staging to master for [`federalist-proxy`](https://github.com/18F/federalist-proxy)
- [x] **3rd:** Successfully merge and deploy staging to master for [`federalist-garden-build`](https://github.com/18F/federalist-garden-build)
- [x] **4th:** Successfully merge and deploy staging to master for [`federalist`](https://github.com/18F/federalist)
- [x] **5th:** update sites set engine = 'node.js' where engine = 'script only'
