### ISSUE TITLE
Create Site Bucket Space for Large Media Files

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#2274]
#### User Story

When a user has a site with a lot of large media files (not suitable for GIT), allow them to upload large media files for their site and return hyper link url to use in their site.

#### Background (Optional)

- (Maybe Redirect requests for branches)[https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html]

#### Acceptance Criteria

- [ ] able to upload large files to S3 via federalistapp site settings
- [ ] pass large file path as env variable (ie: lfs_url) to s3 build process
- [ ] Change made live via deploy to Fedearlist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] enable users to to upload files on the federalistapp UI to store on site's dedicated S3 bucket
- [ ] create environment variable (ie: lfs_url) for builds that lead to S3 large file storage location

**Comment by amirbey** [comment]
to be prioritized in backlog

**Comment by amirbey** [comment]
i was thinking we could consider leveraging our socket.io setup ... and came across this https://www.npmjs.com/package/socket.io-file

**Comment by eddietejeda** [comment]
Can you say more?
