### ISSUE TITLE
Replace Proxy Server

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2441]
#### User Story

A user should be able utilize such features as basic authentication, immutable deployments, custom headers and the platform should be able to have more control. Implementing the Proxy in `node` will allow Federalist Operators to continuously improve and maintain the system.

#### Background (Optional)

The current proxy is implemented in `nginx`, which, while wonderful technology, may not be the best choice for Federalist.  
1.  `nginx` is commonly used in front of web application servers to handle certain cpu-intensive tasks such as:
- TLS termination
- load balancing
- serving static files

However, cloud.gov handles TLS termination and load balancing, while S3 serves static files (with caching in Cloudfront for custom domains). For other tasks, any performance benefits gained by using `nginx` are outweighed by the difficulty in customizing the system to suit our needs.

2. Federalist Operators have much more expertise managing other language/ecosystems, such as `node`, and will be better able to leverage existing resources to develop security-related and user-facing features and operate the Proxy if written in `node`.

#### Acceptance Criteria

- [ ] feature parity with `nginx` proxy
- [ ] Change made live via <TODO>

#### Enhancements
- [ ] request signing to access private s3 buckets
- [ ] basic authentication
- [ ] sso authentication
- [ ] more custom headers
- [ ] dynamic routing / unique / immutable deployments (at domain root)  (enabled via wildcard domains for Pages)
- [ ] Correct routing for SPA preview deployments via all deployments at root of domain above

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
To do:
test plan
monitor
how to roll back
how we notify customers
any compliance responsibilities to the customer
