### ISSUE TITLE
dashboard for Federalist admins

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2457]
#### User Story

A federalist user would like to view build statistics (ie: build time, % failures, ...)

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] investigate/meet to determine what info/statistics to gather and calculate based on Federalist data
- [ ] view site env variable keys and *****
- [ ] view user settings (ie: push notifications)
- [ ] ...
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>
