### ISSUE TITLE
Reduce or eliminate discriminatory or insensitive terminology from our applications

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2706]
#### User Story

As a Federalist user, developer, or manager, I don't want to see or use terminology that is discriminatory or insensitive. This also has the added benefit of using terms that more accurately describe the technical role.

This is fairly straightforward for our own repositories, however, the platform also defaults to the `master` branch when:
- The user creates a site
- We create a new repo from a template

Since we have to opportunity to influence the use of language used by our partners as well, I would like to change the defaults for these operations (leaving existing ones as is) while providing appropriate messaging.

I would really like to get the teams feedback on all of this before moving forward and will put something on the calendar.

#### Background (Optional)

This includes, but is not limited to:
- renaming `master` branches to `main`
- renaming `whitelist`s and `blacklist`s to `allowlist`s and `denylist`s respectively
- more?

#### Acceptance Criteria

- [x] federalist-uswds-jekyll
- [x] federalist-uswds-gatsby
- [x] federalist
- [x] federalist-garden-build
- [x] federalist-builder
- [x] federalist-proxy
- [x] federalist.18f.gov
- [x] federalist-proxy-edge
- [x] Change made live via above deployments.

#### Implementation outline (if higher than "low" effort):

- [x] <TODO>

**Comment by davemcorwin** [comment]
Some places where we reference `master` as a default value:
https://github.com/18F/federalist/blob/staging/frontend/components/AddSite/index.js#L89
https://github.com/18F/federalist/blob/staging/api/models/site.js#L91
https://github.com/18F/federalist/blob/staging/config/templates.js#L5
https://github.com/18F/federalist/blob/staging/config/templates.js#L15
https://github.com/18F/federalist/blob/staging/frontend/components/AddSite/AddRepoSiteForm.jsx#L66

**Comment by davemcorwin** [comment]
Per today's discussion we're going to go forward with these changes. They will be broken down into subsequent issues/
