### ISSUE TITLE
Standalone ATO for Federalist

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#387]
Federalist has an ATO as part of its component websites, but does not have a standalone ATO. 

- [x] Will to take call about startup (11/29)
- [x] https://github.com/18F/federalist/issues/397 (not yet in PRD)
- [x] https://github.com/18F/federalist/issues/399 (not yet in PRD)

To do items here: https://github.com/18F/Infrastructure/issues/625

**Comment by leahbannon** [comment]
Assigning to Adam so he can review 18F/Infrastructure#625 and update with things that are complete and open issues in this repo for things that still need to be done.

**Comment by wslack** [comment]
@el-mapache shouldn't this stay open as a task?

**Comment by el-mapache** [comment]
Yes, I think I clicked on this one by accident! Thanks for the heads up.

**Comment by wslack** [comment]
**Prereqs:**
- [ ] cloud.gov new CRM is ready
- [ ] cloud.gov works with GSA IT to define support for containers or container-like options as part of PATO or ATO
- [ ] New SSP template is ready

**Owned by Federalist**

- [ ] Create architecture options (bearing in mind possible docker host $)
- [ ] Get GSA IT feedback in writing
- [ ] Choose specific strategy, get strategy approved by CISO in writing
- [ ] Execute on strategy (using https://github.com/18F/federalist/issues/398, https://github.com/18F/federalist/issues/399, and more)
- [ ] Begin work on SSP template

Notes from previous retros are [here](https://docs.google.com/document/d/1iarnQ-CZrTXGSy8RFCyp7i-bKYulKpg2-QdhW48dVXQ/edit) and [here](https://docs.google.com/document/d/1tY56SdgNCNwOEABlhNOof_75LrZAP_OBOt6V2NJRPE4/edit).

**Comment by wslack** [comment]
Will to contact GSA IT

**Comment by wslack** [comment]
Meeting happening in next week on this.

**Comment by wslack** [comment]
MEeting with GSA IT next week

**Comment by wslack** [comment]
@davidewarren making subissues today
