### ISSUE TITLE
ATO work for Build

### ISSUE THREAD

**Issue by wslack** [18F/federalist#399]
- [x]  Work with Noah and Diego on evaluating what is needed to properly leverage cloud.gov
- [x] Setup Clair https://github.com/18F/federalist/issues/541
- [x] Refactor Federalist Builder to run tasks on Diego instead of ECS https://github.com/18F/federalist/issues/542
- [x] Setup trusted registry for docker images https://github.com/18F/federalist/issues/543
- [x] Deploy in staging
- [ ] Complete Clair scanning/updates https://github.com/18F/federalist/issues/557
- [ ] Deploy in production

**Comment by wslack** [comment]
The feature for this comes nearly for free with DEAgo. The ability for users vs the platform movement are different things.

**Comment by wslack** [comment]
1. DEAgo - but don't know when it will be available and if cloud.gov will do the extra work to enable us to leverage it.
2. Travis - best if we can do that. We're encrypting variables, but there's a rate limit. (10 requests/ 30 seconds). We could make the queue manager slow down, but that slows down the entire process.
3. CircleCI - much faster, but not sure how to do encryption of tokens needed to clone the repo.
4. Replace with an AMI (not recommended).
5. Many one-off "serverless" ideas like Lambda or **cloud.gov tasks**. A system like that that is ATO'd could be used. Lambda is least likely.

**Comment by NoahKunin** [comment]
@wslack Depending on how you use Lambda, there's no firm blocker there. You would need a service broker though, but that's straightforward.

**Comment by wslack** [comment]
New options:
1) Check when DEAgo is in the cloud.gov roadmap.
2) @jeremiak checking if we can get Circle  to get an API limit we can work with
3) Try and see if there are 1-2 micropurchases we could make to get this app as a worker hack working
4) do it ourselves

**Comment by wslack** [comment]
Set up time with someone on the cloud.gov team to go through how this works.

**Comment by wslack** [comment]
Need to move to using of DEAgo on cloud.gov

**Comment by wslack** [comment]
https://docs.google.com/document/d/1RSW1hEmeSFjEg-bbmLBshuSmHW6ixdBeTc0MIlRw6l0/edit#heading=h.1yslgp3iq0jg

**Comment by jmhooper** [comment]
Moving this to `blocked` until we are in a spot where we can deploy the new build process to production which should check the last box and let us close this.

**Comment by NoahKunin** [comment]
Team - great job on all of this work to date.

**Comment by jseppi** [comment]
This seems like it can be closed because we are (and have been for a long time) using garden docker build containers.

@wslack: please close if that assessment is correct!

**Comment by wslack** [comment]
This is super out of date and can be closed, but we still need to continue build process ATO work, which is happening.
